variable "region" {
  description = "AWS region for all resources."
  type        = string
}

variable "aws_profile" {
  description = "AWS CLI profile. Optional - falls back to AWS_PROFILE env var."
  type        = string
  default     = null
}

variable "name" {
  description = "Deployment name. Used as the VPC identifier."
  type        = string
}

variable "network" {
  description = "Shared VPC settings. One VPC is created and reused by every database."
  type = object({
    vpc_cidr = string
    azs      = list(string)
  })
}

variable "allowed_cidrs" {
  description = "Default CIDR list applied to every DB that doesn't set its own `allowed_cidrs`. Use this for your office VPN egress CIDR(s) so you only update one place. Per-DB `allowed_cidrs` overrides this; per-DB `allowed_cidrs = []` explicitly blocks all direct access."
  type        = list(string)
  default     = []
}

variable "redis_privatelink_arn" {
  description = "Default `redis_privatelink_arn` for every DB that doesn't set its own. null = closed, \"*\" = any AWS principal, ARN or list of ARNs = scoped."
  type        = any
  default     = null
}

variable "redis_secrets_arn" {
  description = "Default `redis_secrets_arn` for every DB that doesn't set its own. null = no resource policy; an ARN or list of ARNs scopes access to those principals. Wildcard access is not supported for secrets."
  type        = any
  default     = null
  validation {
    condition = var.redis_secrets_arn == null ? true : (
      can(tolist(var.redis_secrets_arn))
      ? alltrue([for arn in tolist(var.redis_secrets_arn) : tostring(arn) != "*" && tostring(arn) != ""])
      : tostring(var.redis_secrets_arn) != "*" && tostring(var.redis_secrets_arn) != ""
    )
    error_message = "redis_secrets_arn must be an ARN or list of ARNs; empty strings and wildcard access are not supported."
  }
}

variable "bastion" {
  description = <<-EOT
    Optional bastion EC2 with all DB clients pre-installed and a Makefile for `make sql-shell <db-name>`.
    When enabled, the bastion's SG is added as ingress to every DB so it can connect even when public_access = false.
    SSH password is random_generated by terraform - read it via `terraform output -raw bastion_password`.
  EOT
  type = object({
    enabled       = optional(bool, false)
    instance_type = optional(string, "t3.small")
    # SSH ingress for the bastion. Defaults to the top-level allowed_cidrs (office VPN).
    allowed_ssh_cidrs = optional(list(string))
  })
  default = {}
}

variable "databases" {
  description = <<-EOT
    Map of databases to deploy. The key becomes the identifier on every resource for that DB.
    Engine is required; everything else has a sensible default per engine.

    public_access = true makes the DB's NLB internet-facing and opens the DB port to allowed_cidrs.
    Defaults to false (PrivateLink only).

    Dedicated CDC user creation for MySQL, MariaDB, and SQL Server runs from the Terraform
    runner and requires reachability through the NLB. For a private NLB, run Terraform from
    inside the VPC. Automatic init_sql_file loading runs only when public_access = true; for
    private databases it is skipped so the bundled scripts can be run later from the bastion.

    allowed_cidrs - omitted = inherit the top-level `allowed_cidrs`; set explicitly (even `[]`)
                    to override (e.g. block all direct access on this one DB).

    Per-database ARN settings:
      - omitted or null: inherit the corresponding top-level default
      - []: closed - no external principal is granted access
      - specific ARN or list of ARNs: scoped to those Redis Cloud subscription principals
      - redis_privatelink_arn = "*": any AWS principal can consume the endpoint

    Wildcard access is not supported for redis_secrets_arn.
  EOT
  type        = any
}
